### ISSUE TITLE
只能爬取想读，但是没有在读和读过两个部分

### ISSUE THREAD

**Issue by seanxuu** [JimSunJing/douban_crawler#1]
rt
我也是程序员，如果可以，我也可以帮忙想办法

**Comment by JimSunJing** [comment]
这个脚本没有爬取在读的功能哦。
读过爬取我用的是Selenium库，因为豆瓣读书的“读过”页面未登录直接访问（用了headers和代理ip也还是会被block）是403: Forbidden的状态，但是后来我发现——先访问一次某用户的读书主页再次访问他的读过就不会403，所以用了selenium。
如果有其他的更简易访问豆瓣读过界面的方法希望可以告知我。谢谢帮助。

**Comment by seanxuu** [comment]
> 如果**自动打开的网页**卡在了你的“豆瓣阅读”主页（没有卡住就不要动），你可以点击一下你的读过链接帮助脚本继续运行。

我这里并没有看到自动打开的网页，有点奇怪

**Comment by JimSunJing** [comment]
我觉得可能是chromedriver版本的问题，你可以去README里面找你chrome对应版本的chromedriver试试

**Comment by seanxuu** [comment]
> 我觉得可能是chromedriver版本的问题，你可以去README里面找你chrome对应版本的chromedriver试试

这个问题解决了，新的问题又来了。
`DevTools listening on ws://127.0.0.1:10242/devtools/browser/f928adeb-4fb5-4f37-86f6-c09a8d1216d7
Traceback (most recent call last):
  File "doubanbook.py", line 63, in BRappend
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "doubanbook.py", line 136, in <module>
  File "doubanbook.py", line 129, in main
  File "doubanbook.py", line 91, in ReadBookList
  File "doubanbook.py", line 68, in BRappend
IndexError: list index out of range
[7748] Failed to execute script doubanbook`

我先不管了，搬砖去了。有空再看看。

**Comment by JimSunJing** [comment]
hello, 解决了，你直接拿最新的 doubanbook.py脚本去用吧。

**Comment by seanxuu** [comment]
> hello, 解决了，你直接拿最新的 doubanbook.py脚本去用吧。

ok 但是还是有些错误的地方，等你考完试我们再交流看看吧。考试更重要。
