### ISSUE TITLE
一些思路上的改进

### ISSUE THREAD

**Issue by yuanjingsong** [JimSunJing/douban_crawler#2]
大概看了一下使用方法，猜测您的思路大概是通过 selenium 进行模拟，点击下一页？

其实不用使用selenium模拟，可以直接使用requests 包进行请求。

不用 selenium 的原因还是因为有的用户可能没有安装 chrome ，并且 我测试了一下，在 MacOs 下，即时安装了 chrome 仍然会出现 path 错误。所以 不如使用 requests ，最后统一进行打包。

**Comment by yuanjingsong** [comment]
需要帮助的话，我明天考完试，也可以写 23333

**Comment by JimSunJing** [comment]
哈哈哈我其他都是用request的啊，但是豆瓣读书的防爬虫很奇怪欸，直接request已读页面（collect）会被403的，你可以开一个隐身模式试一下。

**Comment by JimSunJing** [comment]
哇，感谢提供思路我用request.Session()代替了selenium了，十分感谢。
