### ISSUE TITLE
备份豆列的问题

### ISSUE THREAD

**Issue by lavendercmt** [JimSunJing/douban_crawler#6]
self.list_name=soup.h1.text

AttributeError: 'NoneType' object has no attribute 'text'

请问这是什么问题呢？

**Comment by JimSunJing** [comment]
嗯好像是豆瓣豆列标题前后加了个换行符，我修复一下

**Comment by JimSunJing** [comment]
我怀疑你是没有把豆列变成公开的所以访问不了那个豆列。

**Comment by lavendercmt** [comment]
啊确实是有非公开豆列.......

请问关注的豆列能爬吗？

**Comment by JimSunJing** [comment]
可以的只要是公开的就OK，那我先把 issue 关了哦
